insert into `Countries` (`countryId`, `name`, `iso2`, `phoneCode`, `phoneMask`, `currency`, `flag`)

values (1, 'Afghanistan', 'AF', '93', null, 'AFN', '🇦🇫'),
       (2, 'Aland Islands', 'AX', '358-18', null, 'EUR', '🇦🇽'),
       (3, 'Albania', 'AL', '355', null, 'ALL', '🇦🇱'),
       (4, 'Algeria', 'DZ', '213', null, 'DZD', '🇩🇿'),
       (5, 'American Samoa', 'AS', '1-684', null, null,'🇦🇸'),
       (6, 'Andorra', 'AD', '376', null, 'EUR',null),
       (7, 'Angola', 'AO', '244', null, 'AOA',null),
       (8, 'Anguilla', 'AI', '1-264', null, 'XCD',null),
       (9, 'Antarctica', 'AQ', '', null, '',null),
       (10, 'Antigua And Barbuda', 'AG', '1-268', null, 'XCD',null),
       (11, 'Argentina', 'AR', '54', null, 'ARS',null),
       (12, 'Armenia', 'AM', '374', null, 'AMD', '🇦🇲'),
       (13, 'Aruba', 'AW', '297', null, 'AWG',null),
       (14, 'Australia', 'AU', '61', null, 'AUD',null),
       (15, 'Austria', 'AT', '43', null, 'EUR',null),
       (17, 'Bahamas The', 'BS', '1-242', null, 'BSD',null),
       (18, 'Bahrain', 'BH', '973', null, 'BHD',null),
       (19, 'Bangladesh', 'BD', '880', null, 'BDT',null),
       (20, 'Barbados', 'BB', '1-246', null, 'BBD',null),
       (21, 'Belarus', 'BY', '375', null, 'BYR',null),
       (22, 'Belgium', 'BE', '32', null, 'EUR',null),
       (23, 'Belize', 'BZ', '501', null, 'BZD',null),
       (24, 'Benin', 'BJ', '229', null, 'XOF',null),
       (25, 'Bermuda', 'BM', '1-441', null, 'BMD',null),
       (26, 'Bhutan', 'BT', '975', null, 'BTN',null),
       (27, 'Bolivia', 'BO', '591', null, 'BOB',null),
       (29, 'Botswana', 'BW', '267', null, 'BWP',null),
       (30, 'Bouvet Island', 'BV', '', null, 'NOK',null),
       (31, 'Brazil', 'BR', '55', null, 'BRL',null),
       (32, 'British Indian Ocean Territory', 'IO', '246', null, 'USD',null),
       (33, 'Brunei', 'BN', '673', null, 'BND',null),
       (34, 'Bulgaria', 'BG', '359', null, 'BGN',null),
       (35, 'Burkina Faso', 'BF', '226', null, 'XOF',null),
       (36, 'Burundi', 'BI', '257', null, 'BIF',null),
       (37, 'Cambodia', 'KH', '855', null, 'KHR',null),
       (38, 'Cameroon', 'CM', '237', null, 'XAF',null),
       (39, 'Canada', 'CA', '1', null, 'CAD',null),
       (40, 'Cape Verde', 'CV', '238', null, 'CVE',null),
       (41, 'Cayman Islands', 'KY', '1-345', null, 'KYD',null),
       (42, 'Central African Republic', 'CF', '236', null, 'XAF',null),
       (43, 'Chad', 'TD', '235', null, 'XAF',null),
       (44, 'Chile', 'CL', '56', null, 'CLP',null),
       (45, 'China', 'CN', '86', null, 'CNY',null),
       (46, 'Christmas Island', 'CX', '61', null, 'AUD',null),
       (47, 'Cocos (Keeling) Islands', 'CC', '61', null, 'AUD',null),
       (48, 'Colombia', 'CO', '57', null, 'COP',null),
       (49, 'Comoros', 'KM', '269', null, 'KMF',null),
       (50, 'Congo', 'CG', '242', null, 'XAF',null),
       (51, 'Congo The Democratic Republic Of The', 'CD', '243', null, 'CDF',null),
       (52, 'Cook Islands', 'CK', '682', null, 'NZD',null),
       (53, 'Costa Rica', 'CR', '506', null, 'CRC',null),
       (54, 'Cote D&#039;Ivoire (Ivory Coast)', 'CI', '225', null, 'XOF',null),
       (55, 'Croatia (Hrvatska)', 'HR', '385', null, 'HRK',null),
       (56, 'Cuba', 'CU', '53', null, 'CUP',null),
       (57, 'Cyprus', 'CY', '357', null, 'EUR',null),
       (58, 'Czech Republic', 'CZ', '420', null, 'CZK',null),
       (59, 'Denmark', 'DK', '45', null, 'DKK',null),
       (60, 'Djibouti', 'DJ', '253', null, 'DJF',null),
       (61, 'Dominica', 'DM', '1-767', null, 'XCD',null),
       (63, 'East Timor', 'TL', '670', null, 'USD',null),
       (64, 'Ecuador', 'EC', '593', null, 'USD',null),
       (65, 'Egypt', 'EG', '20', null, 'EGP',null),
       (66, 'El Salvador', 'SV', '503', null, 'USD',null),
       (67, 'Equatorial Guinea', 'GQ', '240', null, 'XAF',null),
       (68, 'Eritrea', 'ER', '291', null, 'ERN',null),
       (69, 'Estonia', 'EE', '372', null, 'EUR',null),
       (70, 'Ethiopia', 'ET', '251', null, 'ETB',null),
       (71, 'Falkland Islands', 'FK', '500', null, 'FKP',null),
       (72, 'Faroe Islands', 'FO', '298', null, 'DKK',null),
       (73, 'Fiji Islands', 'FJ', '679', null, 'FJD',null),
       (74, 'Finland', 'FI', '358', null, 'EUR',null),
       (75, 'France', 'FR', '33', null, 'EUR',null),
       (76, 'French Guiana', 'GF', '594', null, 'EUR',null),
       (77, 'French Polynesia', 'PF', '689', null, 'XPF',null),
       (78, 'French Southern Territories', 'TF', '', null, 'EUR',null),
       (79, 'Gabon', 'GA', '241', null, 'XAF',null),
       (80, 'Gambia The', 'GM', '220', null, 'GMD',null),
       (81, 'Georgia', 'GE', '995', null, 'GEL',null),
       (82, 'Germany', 'DE', '49', null, 'EUR',null),
       (83, 'Ghana', 'GH', '233', null, 'GHS',null),
       (84, 'Gibraltar', 'GI', '350', null, 'GIP',null),
       (85, 'Greece', 'GR', '30', null, 'EUR',null),
       (86, 'Greenland', 'GL', '299', null, 'DKK',null),
       (87, 'Grenada', 'GD', '1-473', null, 'XCD',null),
       (88, 'Guadeloupe', 'GP', '590', null, 'EUR',null),
       (89, 'Guam', 'GU', '1-671', null, 'USD',null),
       (90, 'Guatemala', 'GT', '502', null, 'GTQ',null),
       (92, 'Guinea', 'GN', '224', null, 'GNF',null),
       (93, 'Guinea-Bissau', 'GW', '245', null, 'XOF',null),
       (94, 'Guyana', 'GY', '592', null, 'GYD',null),
       (95, 'Haiti', 'HT', '509', null, 'HTG',null),
       (96, 'Heard and McDonald Islands', 'HM', ' ', null, 'AUD',null),
       (97, 'Honduras', 'HN', '504', null, 'HNL',null),
       (98, 'Hong Kong S.A.R.', 'HK', '852', null, 'HKD',null),
       (99, 'Hungary', 'HU', '36', null, 'HUF',null),
       (100, 'Iceland', 'IS', '354', null, 'ISK',null),
       (101, 'India', 'IN', '91', null, 'INR',null),
       (102, 'Indonesia', 'ID', '62', null, 'IDR',null),
       (103, 'Iran', 'IR', '98', null, 'IRR',null),
       (104, 'Iraq', 'IQ', '964', null, 'IQD',null),
       (105, 'Ireland', 'IE', '353', null, 'EUR',null),
       (106, 'Israel', 'IL', '972', null, 'ILS',null),
       (107, 'Italy', 'IT', '39', null, 'EUR',null),
       (108, 'Jamaica', 'JM', '1-876', null, 'JMD',null),
       (109, 'Japan', 'JP', '81', null, 'JPY',null),
       (111, 'Jordan', 'JO', '962', null, 'JOD',null),
       (112, 'Kazakhstan', 'KZ', '7', null, 'KZT',null),
       (113, 'Kenya', 'KE', '254', null, 'KES',null),
       (114, 'Kiribati', 'KI', '686', null, 'AUD',null),
       (115, 'Korea North\n', 'KP', '850', null, 'KPW',null),
       (116, 'Korea South', 'KR', '82', null, 'KRW',null),
       (117, 'Kuwait', 'KW', '965', null, 'KWD',null),
       (118, 'Kyrgyzstan', 'KG', '996', null, 'KGS',null),
       (119, 'Laos', 'LA', '856', null, 'LAK',null),
       (120, 'Latvia', 'LV', '371', null, 'EUR',null),
       (121, 'Lebanon', 'LB', '961', null, 'LBP',null),
       (122, 'Lesotho', 'LS', '266', null, 'LSL',null),
       (123, 'Liberia', 'LR', '231', null, 'LRD',null),
       (124, 'Libya', 'LY', '218', null, 'LYD',null),
       (125, 'Liechtenstein', 'LI', '423', null, 'CHF',null),
       (126, 'Lithuania', 'LT', '370', null, 'LTL',null),
       (127, 'Luxembourg', 'LU', '352', null, 'EUR',null),
       (128, 'Macau S.A.R.', 'MO', '853', null, 'MOP',null),
       (129, 'Macedonia', 'MK', '389', null, 'MKD',null),
       (130, 'Madagascar', 'MG', '261', null, 'MGA',null),
       (131, 'Malawi', 'MW', '265', null, 'MWK',null),
       (132, 'Malaysia', 'MY', '60', null, 'MYR',null),
       (133, 'Maldives', 'MV', '960', null, 'MVR',null),
       (134, 'Mali', 'ML', '223', null, 'XOF',null),
       (135, 'Malta', 'MT', '356', null, 'EUR',null),
       (137, 'Marshall Islands', 'MH', '692', null, 'USD',null),
       (138, 'Martinique', 'MQ', '596', null, 'EUR',null),
       (139, 'Mauritania', 'MR', '222', null, 'MRO',null),
       (140, 'Mauritius', 'MU', '230', null, 'MUR',null),
       (141, 'Mayotte', 'YT', '262', null, 'EUR',null),
       (142, 'Mexico', 'MX', '52', null, 'MXN',null),
       (143, 'Micronesia', 'FM', '691', null, 'USD',null),
       (144, 'Moldova', 'MD', '373', null, 'MDL',null),
       (145, 'Monaco', 'MC', '377', null, 'EUR',null),
       (146, 'Mongolia', 'MN', '976', null, 'MNT',null),
       (147, 'Montenegro', 'ME', '382', null, 'EUR',null),
       (148, 'Montserrat', 'MS', '1-664', null, 'XCD',null),
       (149, 'Morocco', 'MA', '212', null, 'MAD',null),
       (150, 'Mozambique', 'MZ', '258', null, 'MZN',null),
       (151, 'Myanmar', 'MM', '95', null, 'MMK',null),
       (152, 'Namibia', 'NA', '264', null, 'NAD',null),
       (153, 'Nauru', 'NR', '674', null, 'AUD',null),
       (154, 'Nepal', 'NP', '977', null, 'NPR',null),
       (155, 'Netherlands Antilles', 'AN', '', null, '',null),
       (156, 'Netherlands The', 'NL', '31', null, 'EUR',null),
       (157, 'New Caledonia', 'NC', '687', null, 'XPF',null),
       (158, 'New Zealand', 'NZ', '64', null, 'NZD',null),
       (159, 'Nicaragua', 'NI', '505', null, 'NIO',null),
       (160, 'Niger', 'NE', '227', null, 'XOF',null),
       (161, 'Nigeria', 'NG', '234', null, 'NGN',null),
       (162, 'Niue', 'NU', '683', null, 'NZD',null),
       (163, 'Norfolk Island', 'NF', '672', null, 'AUD',null),
       (164, 'Northern Mariana Islands', 'MP', '1-670', null, 'USD',null),
       (165, 'Norway', 'NO', '47', null, 'NOK',null),
       (166, 'Oman', 'OM', '968', null, 'OMR',null),
       (167, 'Pakistan', 'PK', '92', null, 'PKR',null),
       (168, 'Palau', 'PW', '680', null, 'USD',null),
       (169, 'Palestinian Territory Occupied', 'PS', '970', null, 'ILS',null),
       (170, 'Panama', 'PA', '507', null, 'PAB',null),
       (171, 'Papua new Guinea', 'PG', '675', null, 'PGK',null),
       (172, 'Paraguay', 'PY', '595', null, 'PYG',null),
       (173, 'Peru', 'PE', '51', null, 'PEN',null),
       (174, 'Philippines', 'PH', '63', null, 'PHP',null),
       (175, 'Pitcairn Island', 'PN', '870', null, 'NZD',null),
       (176, 'Poland', 'PL', '48', null, 'PLN',null),
       (177, 'Portugal', 'PT', '351', null, 'EUR',null),
       (178, 'Puerto Rico', 'PR', '1-787', null, 'USD',null),
       (179, 'Qatar', 'QA', '974', null, 'QAR',null),
       (180, 'Reunion', 'RE', '262', null, 'EUR',null),
       (181, 'Romania', 'RO', '40', null, 'RON',null),
       (182, 'Russia', 'RU', '7', null, 'RUB',null),
       (183, 'Rwanda', 'RW', '250', null, 'RWF',null),
       (184, 'Saint Helena', 'SH', '290', null, 'SHP',null),
       (185, 'Saint Kitts And Nevis', 'KN', '1-869', null, 'XCD',null),
       (186, 'Saint Lucia', 'LC', '1-758', null, 'XCD',null),
       (187, 'Saint Pierre and Miquelon', 'PM', '508', null, 'EUR',null),
       (188, 'Saint Vincent And The Grenadines', 'VC', '1-784', null, 'XCD',null),
       (189, 'Saint-Barthelemy', 'BL', '590', null, 'EUR',null),
       (190, 'Saint-Martin (French part)', 'MF', '590', null,'EUR',null),
       (191, 'Samoa', 'WS', '685', null,'WST',null),
       (192, 'San Marino', 'SM', '378', null,'EUR',null),
       (193, 'Sao Tome and Principe', 'ST', '239', null,'STD',null),
       (194, 'Saudi Arabia', 'SA', '966', null,'SAR',null),
       (195, 'Senegal', 'SN', '221', null,'XOF',null),
       (196, 'Serbia', 'RS', '381', null,'RSD',null),
       (197, 'Seychelles', 'SC', '248', null,'SCR',null),
       (198, 'Sierra Leone', 'SL', '232', null,'SLL',null),
       (199, 'Singapore', 'SG', '65', null,'SGD',null),
       (200, 'Slovakia', 'SK', '421', null,'EUR',null),
       (201, 'Slovenia', 'SI', '386', null,'EUR',null),
       (202, 'Solomon Islands', 'SB', '677', null,'SBD',null),
       (203, 'Somalia', 'SO', '252', null,'SOS',null),
       (204, 'South Africa', 'ZA', '27', null,'ZAR',null),
       (205, 'South Georgia', 'GS', '', null,'GBP',null),
       (206, 'South Sudan', 'SS', '211', null,'SSP',null),
       (207, 'Spain', 'ES', '34', null,'EUR',null),
       (208, 'Sri Lanka', 'LK', '94', null,'LKR',null),
       (209, 'Sudan', 'SD', '249', null,'SDG',null),
       (210, 'Suriname', 'SR', '597', null,'SRD',null),
       (211, 'Svalbard And Jan Mayen Islands', 'SJ', '47', null,'NOK',null),
       (212, 'Swaziland', 'SZ', '268', null,'SZL',null),
       (213, 'Sweden', 'SE', '46', null,'SEK',null),
       (214, 'Switzerland', 'CH', '41', null,'CHF',null),
       (215, 'Syria', 'SY', '963', null,'SYP',null),
       (216, 'Taiwan', 'TW', '886', null,'TWD',null),
       (217, 'Tajikistan', 'TJ', '992', null,'TJS',null),
       (218, 'Tanzania', 'TZ', '255', null,'TZS',null),
       (219, 'Thailand', 'TH', '66', null,'THB',null),
       (220, 'Togo', 'TG', '228', null,'XOF',null),
       (221, 'Tokelau', 'TK', '690', null,'NZD',null),
       (222, 'Tonga', 'TO', '676', null,'TOP',null),
       (223, 'Trinidad And Tobago', 'TT', '1-868', null,'TTD',null),
       (224, 'Tunisia', 'TN', '216', null,'TND',null),
       (225, 'Turkey', 'TR', '90', null,'TRY',null),
       (226, 'Turkmenistan', 'TM', '993', null,'TMT',null),
       (227, 'Turks And Caicos Islands', 'TC', '1-649', null,'USD',null),
       (228, 'Tuvalu', 'TV', '688', null,'AUD',null),
       (229, 'Uganda', 'UG', '256', null,'UGX',null),
       (230, 'Ukraine', 'UA', '380', null,'UAH',null),
       (231, 'United Arab Emirates', 'AE', '971', null,'AED',null),
       (232, 'United Kingdom', 'GB', '44', null,'GBP',null),
       (233, 'United States', 'US', '1', null,'USD',null),
       (234, 'United States Minor Outlying Islands', 'UM', '1', null,'USD',null),
       (235, 'Uruguay', 'UY', '598', null,'UYU',null),
       (236, 'Uzbekistan', 'UZ', '998', null,'UZS',null),
       (237, 'Vanuatu', 'VU', '678', null,'VUV',null),
       (238, 'Vatican City State (Holy See)', 'VA', '379', null,'EUR',null),
       (239, 'Venezuela', 'VE', '58', null,'VEF',null),
       (240, 'Vietnam', 'VN', '84', null,'VND',null),
       (241, 'Virgin Islands (British)', 'VG', '1-284', null,'USD',null),
       (242, 'Virgin Islands (US)', 'VI', '1-340', null,'USD',null),
       (243, 'Wallis And Futuna Islands', 'WF', '681', null,'XPF',null),
       (244, 'Western Sahara', 'EH', '212', null,'MAD',null),
       (245, 'Yemen', 'YE', '967', null,'YER',null),
       (246, 'Zambia', 'ZM', '260', null,'ZMK',null),
       (247, 'Zimbabwe', 'ZW', '263', null,'ZWL', null);
